### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by 1271** [PintsizedSix40/DiscordBridge#1]
Hi. I would like more detailed instructions on how to configure the plugin.
It is not clear where to get data for the plugin itself:

```yaml
loaded: 'true'
ip: localhost
port: 1033
name: name ?? < what is it? bot name?
auth: ??? < Where to get this data?
integration:
   commands:
     balance: true
     spawn: true
   usechatformatting: true
```

Thanks
